language: python
python:
 - "3.8"
install:
 - pip install -r requirements.txt

jobs:
 include:
  - stage test
   script: python -m unittest test.test_app
  -
   script: python -m unittest test.test_graph
  - stage: GitHub Release
  if: branch = master
  deploy:
   provider: releases
   api_key: $GITHUB_OAUTH_TOKEN
   on:
    tags: true