language: python
python:
 - "3.8"

stage:
  - test
  - name: GitHub Release
    if: branch = master

install:
 - pip install -r requirements.txt

jobs:
 include:
  - stage: test
    script: python -m unittest test.test_app
    name: "app functions test"


  - script: python -m unittest test.test_graph
    name: "graph class test"


  - stage: GitHub Release
    deploy:
     provider: releases
     api_key: $GITHUB_OAUTH_TOKEN
     on:
       tags: true